version: "3.9"

services:
  # Our Postgres database
  db: # db configuration already set the main conmpose file.
    ports: # Expose ports so that apps not running via docker compose can connect to them.
      - 5432:5432 # format here is "port on our machine":"port on container"

  # Adminer provides a nice little web UI to connect to databases
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula # Pick a theme - https://github.com/vrana/adminer/tree/master/designs
    ports:
      - 3333:8080
#docker compose exec -it db psql -U hashem -d lenslocked
# host=localhost port=5432 user=hashem password=4g5gbook dbname=lenslocked sslmode=disable
