version: "3.9"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    # to assign a volume for the images inside of our container
    volumes: -./images:/app/images

    # this is for testing porposes.
    # TODO: remove Before deploying
    ports:
      - 3000:3000

    # services need to be ready before this service is created
    depends_on:
      # our db service
      - db
